### ISSUE TITLE
Use local kafka ,get  garbled messages use mirrormaker

### ISSUE THREAD

**Issue by AlanWangHongQiang** [Nasdaq/CloudDataService#10]
I use mirror maker to make NLSUTP.stream to my local kafka but when I consume those message , it show garbled messages like below :
![image](https://user-images.githubusercontent.com/22342018/77393742-a792ca00-6dd8-11ea-9026-b2a138bed7bb.png)
I see SDK Code and I assume I should use schema to format them?
I use C#.

**Comment by ruchirvaninasdaq** [comment]
Hello @AlanWangHongQiang : It is expected to see like this as its Avro message  (ByteArray Serialized). You have to deserialize the message using this java example (https://github.com/Nasdaq/CloudDataService/blob/master/ncds-sdk/src/main/java/com/nasdaq/ncdsclient/internal/AvroDeserializer.java).

You can create your Desealizer class in C# also using this (https://github.com/confluentinc/confluent-kafka-dotnet/blob/9617c9e8ecd30189d01fa47e266ca65952e4cdfb/src/Confluent.Kafka/Deserializers.cs#L237)

Please let me know if you have any more questions.
