### ISSUE TITLE
Add system spec

### ISSUE THREAD

**Issue by MatthiasEgli** [Nasdaq/CloudDataService#16]
What kind of system specs are required to support e.g. NASDAQ Totalview streams? How many messages/updates per second are to be expected?

**Comment by ruchirvaninasdaq** [comment]
What kind of system specs are required to support e.g. NASDAQ Totalview streams?
- http://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/Totalview-ITCH-cloud.pdf

How many messages/updates per second are to be expected?
http://www.nasdaqtrader.com/content/ProductsServices/DataProducts/TotalView/TotalViewProFactSheet.pdf

**Comment by MatthiasEgli** [comment]
Both documents don't contain this information. This issue is not solved.

**Comment by ruchirvaninasdaq** [comment]
@MatthiasEgli : 
Current Bandwidth Recommendation (message sizes, peaks, volume, throughput, etc)
http://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/bandwidthreport.xls
Monthly Peak Message Rate Statistics (message sizes, peaks, volume, throughput, etc)
http://www.nasdaqtrader.com/content/technicalsupport/dataproducts/fifstats.xls
