### ISSUE TITLE
Can you pull 1 minute data with Data on demand?

### ISSUE THREAD

**Issue by noam2** [Nasdaq/CloudDataService#22]

**Comment by ruchirvaninasdaq** [comment]
SDK on this repo provides ticks data with streaming API based on apache kafka.

It is possible to pull aggregated minute data with the data on demand product using the summarized trades endpoint. You can set the trade_period as 1 and the trade_precision as "MINUTE".  This will return aggregated data for every minute within your time range.
The documentation for the same is : https://dataondemand.nasdaq.com/docs/index.html#summarized-trades-data .
 
Please let us know if you need more information.

**Comment by noam2** [comment]
Yes! that is what I thought, it's not that clear though haha. What is the first sentence you wrote in the message here about the SDK, did not understand it ?

also, yes I have a few more questions on this:

- In the docs it says 'First trade' and 'Last trade'. Does that mean OHLCV ? bcs it does not state it like that. I am talking about a way to pull aggregated data with all the eligibility rules etc'. In the end of day section it does refer to it as OHLCV but in the summarized it does not for some reason, just want to make sure it will return valid 1 minute bars.

- another thing is here in this doc : http://www.nasdaqtrader.com/content/productsservices/dataproducts/dod/data-on-demand_faq.pdf . it says that one day of trades data is 0.201 GB for all US equities. We have some data and that is clearly in correct as it's somewhere between 4-5GB (only trades). So wanted to know how do those numbers were determined ? 1 year of trades is 52 GB ? does not seem right to me, can you double check?

- Is there a way to get a trail to test the API endpoints for a day or 2?

- Is the historical data unadjusted or adjusted data? for splits etc.

- Does the data contain delisted and name changes tickers? so if a ticker was delisted in 2018 for example will you have it until that point? same as for symbol changes ?

- Do we have to set up a UTP agreement for redistribution ?

Thanks, hoping to hear from you as soon as you can.

**Comment by noam2** [comment]
Also, what is the best way to subscribe to the product ?

**Comment by ruchirvaninasdaq** [comment]
We provide streaming service for data as well as REST api service. 

This repo has an SDK for streaming service. Where you can subscribe to the different streams. 

We also have REST api service for requesting trades, quotes and analytics. https://dataondemand.nasdaq.com/docs/#introduction.

**Comment by noam2** [comment]
@ruchirvaninasdaq can you answer my other questions pls ?

**Comment by ruchirvaninasdaq** [comment]
@noam2 : You can send an email with all question to `datasales@nasdaq.com`. You will be able to get all answers and subscribe to the product also.

**Comment by noam2** [comment]
Can you address some of the technical questions here about the data? @ruchirvaninasdaq
